---
version: '2'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=*
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development_password
      - POSTGRES_DB=ccpa
    depends_on:
      - db
  db:
    # 12 is the latest version offered by Heroku
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development_password
      - POSTGRES_DB=ccpa
