---
version: '2'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=*
      - NODE_ENV=development
      - HTTP_SESSION_KEY=development_session_key
      - ADMIN_PASSWORD=development_admin_password
      - DATABASE_URL=postgres://postgres:development_postgres_password@db:5432/ccpa
    depends_on:
      - db
  db:
    # 12 is the latest version offered by Heroku
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development_postgres_password
      - POSTGRES_DB=ccpa
